version: '3'
dotenv:
  - ".env"
tasks:
  exec:
    desc: "Access docker container"
    cmds:
      - "docker exec -it budgetcontrol-ms-wallets /bin/bash"

  start:
    desc: "Start docker container"
    cmds:
      - "docker-compose -f docker-compose.yml -f docker-compose.db.yml up -d"

  stop:
    desc: "Stop docker container"
    cmds:
      - "docker-compose -f docker-compose.yml -f docker-compose.db.yml down"

    