name: Deploy Wallet application

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

permissions:
  contents: read


jobs:

  run-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, mysql, pdo, pdo_mysql
        ini-values: post_max_size=256M, upload_max_filesize=256M
        coverage: none

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env example
      run: cp .env.example .env

    - name: Run database migrations and seeders
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: test_db
        DB_USERNAME: root
        DB_PASSWORD: root
      run: |
        vendor/bin/phinx migrate
        vendor/bin/phinx seed:run

    - name: Run PHPUnit tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: test_db
        DB_USERNAME: root
        DB_PASSWORD: root
      run: vendor/bin/phpunit test
      
  deploy_job:
    runs-on: ubuntu-latest
    environment: dev
    name: deploy
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: deploy file
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
              username: ${{ secrets.SFTP_USER }} 
              server: ${{ secrets.SFTP_HOST }} 
              password: ${{ secrets.SFTP_PASSWORD }} 
              port:  ${{ secrets.SFTP_PORT }}
              local_path: '.'
              remote_path: ${{ secrets.SFTP_PATH }}
              sftpArgs: '-o ConnectTimeout=5'

        - name: executing composer install
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.SFTP_HOST }}
            username: ${{ secrets.SFTP_USER }}
            password: ${{ secrets.SFTP_PASSWORD }}
            port:  ${{ secrets.SFTP_PORT }}
            script: docker exec budgetcontrol-ms-wallets composer install
  
